version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: rent_db
    restart: always
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 7000:5432

#  backend:
#    container_name: rent_api
#    build:
#      context: ../backend
#      dockerfile: container/Dockerfile
#    ports:
#      - "5001:5001"
#
#  frontend:
#    container_name: rent_frontend
#    build:
#      context: ../frontend
#      dockerfile: container/Dockerfile
#    ports:
#      - "5000:80"
#    depends_on:
#      - backend
